### PR TITLE
Make game

### PR DESCRIPTION
**Pull request by daudi13**
## In this project I:
- I sent and received data from the Leaderboard API
- Created a new game with a name of my choosing
- Implemented the refresh button function
- Implemented the submit button function
- Implemented async and await Javascript feature to consume the API

### CODE REVIEW

**Review by Kingstalux — CHANGES_REQUESTED** [review]
Hi @daudi13 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f744b797263304e546c4563475764546870342f67697068792e676966


## Highlights
✔️ Good pull request description
✔️ Professional README file
✔️ Linters are passing

## Required Changes ♻️
- [x] I keep getting this error when I start your live server. I suggest you clone your repo afresh from Github in order to address this issue 👍 
- Error message:
{A2C9F2F9-2D4D-447F-BDDC-3E4CE001D5F9} png
- [ ] (OPTIONAL) It would be great if you could deploy your project and provide the correct link  in your README file to make it more professional 💯 


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by elyor-doniyorov — CHANGES_REQUESTED** [review]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- [ ] I still keep getting the child completion error that was as requested change by the previous reviewer. Kindly fix that issue and request another review. You can read and use [this page](https://stackoverflow.com/questions/43494794/webpack-html-webpack-plugin-error-child-compilation-failed) if you find it helpful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by daudi13** [comment]
@elyor-doniyorov I tried the changes you suggeted on stackoverflow but none is working. It is hard to find the errors from my end because I just can't see them. here is a video of me trying to clone my repo to replicate the errors. As you will observe my project is working well on my local mashine. I had also asked my partners to clone the repo but only one partner using Windows was able to see the error the two of us with Linus OS never had errors. I'm also available for a zoom if you want to explore this further. In the meantime I'm starting work on my last project.

https://drive.google.com/file/d/1sD5RwV76CMOdHRyaOe7BTkTOjAvFzi_6/view?usp=sharing

*Please also check my live link on my README.md

**Review by sinansevgi — COMMENTED** [review]
Hello @daudi13  👋,

_This is an additional review as a result of the second opinion request._

Windows and Linux resolve paths differently. 
Folder names that have no `.` (current directory symbol) in front of them in your `webpack.config.js` file can be resolved with Linux without an issue, but on Windows, this path will cause errors like previous reviewers are having.

Please update your `webpack.config.js` file and be sure all paths are configured correctly. (If you haven't fully updated yet after our Slack chat)

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)


Keep rocking 🚀! 
Sinan Sevgi

**Comment by daudi13** [comment]
> Hello @daudi13 wave,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Windows and Linux resolve paths differently. Folder names that have no `.` (current directory symbol) in front of them in your `webpack.config.js` file can be resolved with Linux without an issue, but on Windows, this path will cause errors like previous reviewers are having.
> 
> Please update your `webpack.config.js` file and be sure all paths are configured correctly. (If you haven't fully updated yet after our Slack chat)
> 
> As this was the only reason that your project was not approved it will be approved as soon as possible. Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)
> 
> Keep rocking rocket! Sinan Sevgi

I have fixed the issue. I can confirm that the code is running on window OS. Thank you for your help

**Review by ReshyResh — APPROVED** [review]
# Hi @daudi13 , 

### Good job addressing the issues presented, I'm glad this was sorted out!
#### Your project is complete!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
